services:
  - type: web
    name: mywagtail
    plan: free
    env: python
    startCommand: |
      python manage.py migrate --noinput
      python manage.py createsuperuser --noinput --username admin
      python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: "8000"
